### PR TITLE
Fix issue with `placeDetails` being undefined

### PR DESCRIPTION
**Pull request by knownasilya**

### CODE REVIEW

**Comment by knownasilya** [comment]
Sweet, now just to publish the fixed version :smile:

**Comment by sgruhier** [comment]
done

**Comment by knownasilya** [comment]
@sgruhier seems like the dist is the same as the previous version.

**Comment by sgruhier** [comment]
damned!
fixed

**Comment by knownasilya** [comment]
Haha, there should be a 'pre-publish' hook for bower, so that it builds your stuff.

**Pull request merged**
